Pagina/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls)),
        path('admin/', admin.site.urls),
        path('', include('productos.urls', namespace='productos')),
        path('accounts/', include('accounts.urls', namespace='accounts')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns = [
        path('admin/', admin.site.urls),
        path('', include('productos.urls', namespace='productos')),
        path('accounts/', include('accounts.urls', namespace='accounts')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productos/urls.py
from django.urls import path
from . import views
app_name = 'productos'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('producto/<slug:slug>/',
         views.ProductoDetailView.as_view(), name='producto_detail'),
    path('contacto/', views.contactoView, name='contacto'),
    path('crear/', views.AgregarProducto.as_view(), name='crear'),
    path('productos/', views.ProductList.as_view(), name='list')
]

productos/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django.urls import reverse
# Create your models here.
User = get_user_model()


class Producto(models.Model):
    nombre = models.CharField(max_length=60, unique=True)
    precio = models.FloatField()
    stock = models.IntegerField(blank=True, null=True)
    color = models.CharField(max_length=15, blank=True, null=True)
    imagen = models.ImageField()
    slug = models.SlugField(blank=True, null=True)
    talles = models.CharField(max_length=3)
    categoria = models.CharField(choices=[('C', 'Carteras'), ('Z', 'Zapatos'), ('J', 'Jeans'), (
        'ZA', 'Zapatillas'), ('V', 'Vestidos'), ('A', 'Accesorios'), ('B', 'Botas')], max_length=15, null=True, blank=True)
    descripcion = models.TextField(blank=True, null=True, max_length=256)
    imagen2 = models.ImageField(blank=True, null=True)
    imagen3 = models.ImageField(blank=True, null=True)
    imagen4 = models.ImageField(blank=True, null=True)
    imagen5 = models.ImageField(blank=True, null=True)
    caracteristica1 = models.CharField(blank=True, null=True, max_length=30)
    caracteristica2 = models.CharField(blank=True, null=True, max_length=30)
    caracteristica3 = models.CharField(blank=True, null=True, max_length=30)
    caracteristica4 = models.CharField(blank=True, null=True, max_length=30)

    def __str__(self):
        return self.nombre

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nombre)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("productos:producto_detail", kwargs={"slug": self.slug})

productos/forms.py
from django import forms
from phonenumber_field.formfields import PhoneNumberField


class ContactForm(forms.Form):
    nombre = forms.CharField(max_length=50, required=True, widget=forms.TextInput(
        attrs={'placeholder': ('Nombre Completo'), 'id': ('from-name'), 'class': ('form-control')}))
    email = forms.EmailField(required=True, widget=forms.TextInput(
        attrs={'placeholder': ('Email'), 'id': ('from-email'), 'class': ("form-control")}))
    telefono = PhoneNumberField(widget=forms.TextInput(attrs={'placeholder': ('Telefono'), 'id': ('from-phone'), 'class': ('form-control')}),
                                label=("Telefono"), required=False)
    horario = forms.ChoiceField(
        choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], required=False, widget=forms.Select(attrs={'class': ('form-control'), 'id': ('from-calltime')}))
    comentarios = forms.CharField(
        max_length=256, widget=forms.Textarea(attrs={'class': ('form-control'), 'id': ('from-comments'), 'rows': ('5'), 'placeholder': ('Enter Comments')}), required=False)

    def __str__(self):
        return self.email

productos/views.py
from django.shortcuts import render
from django.views import generic
from . import models
from . import forms
from Pagina.settings import EMAIL_HOST_USER
from django.core.mail import send_mail
import random
from django.shortcuts import get_object_or_404
# Create your views here.


class IndexView(generic.ListView):
    model = models.Producto
    template_name = 'productos/index.html'


class ProductoDetailView(generic.DetailView):
    model = models.Producto
    template_name = 'productos/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = get_object_or_404(
            models.Producto, slug=self.kwargs.get('slug'))
        qs = models.Producto.objects.filter(
            categoria=product.categoria).exclude(slug=product.slug)
        context['related'] = qs
        return context


def contactoView(request):
    contacto = forms.ContactForm()
    if request.method == 'POST':
        contacto = forms.ContactForm(request.POST)
        subject = 'Dakota Store: Nuevo mensaje de ' + \
            str(contacto['nombre'].value())
        message = 'Dakota Store, ' + \
            str(contacto['nombre'].value()) + \
            ' se ha comunicado contigo.\n' + 'Email: ' + str(contacto['email'].value()) + '\nTelefono: ' + str(
                contacto['telefono'].value()) + '\nHorario preferente de llamada: ' + str(contacto['horario'].value()) + '\nComentarios adicionales: ' + str(contacto['comentarios'].value())
        recipient = EMAIL_HOST_USER
        send_mail(subject, message, EMAIL_HOST_USER, [recipient])
        return render(request, 'productos/contacto.html', {'mensaje': 'Tu contacto fue enviado con exito.', 'form': forms.ContactForm()})
    return render(request, 'productos/contacto.html', {'form': contacto})


class ProductList(generic.ListView):
    model = models.Producto
    template_name = 'productos/list.html'


class AgregarProducto(generic.CreateView):
    model = models.Producto
    template_name = 'productos/agregar.html'
    fields = ['nombre', 'precio', 'stock', 'color', 'imagen', 'talles', 'categoria', 'descripcion',
              'imagen2', 'imagen3', 'imagen4', 'imagen5', 'caracteristica1', 'caracteristica2', 'caracteristica3', 'caracteristica4']

productos/templates/productos/agregar.html
{% extends 'header.html' %}
{% load bootstrap4 %}

{% block body_block %}
<div class="container">
    <h1 class="bettertext">Agregar producto</h1>
    <form method="post">
        <div class="bettertext">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-primary" value="save">Guardar</button>
        </div>
    </form>
</div>
<hr>
{% include 'footer.html' %}
{% endblock %}

productos/templates/productos/contacto.html
{% extends 'header.html' %}
{% load static %}


{% block body_block%}
<div class="container">

    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'productos:index'%}" style="color: black;"><span>Inicio</span></a>
        </li>
        <li class="breadcrumb-item"><strong><span>Contacto</span></strong></li>
    </ol>
    <div class="container-fluid">
        <hr>
        <form action="" method="POST" id="contactForm" style="padding-bottom: 50px;">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-md-6">
                    <div id="successfail"></div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-12 col-md-6" id="message" style="padding-right: 30px;">
                    <h2 class="h4"><i class="fa fa-envelope"></i>&nbsp;Contactanos<small><small
                                class="required-input">&nbsp;(*requerido)</small></small>
                    </h2>
                    <h4 style="color: green;">{{ mensaje }}</h4>
                    <div class="form-group"><label for="from-name">Nombre</label><span class="required-input">*</span>
                        <div class="input-group" style="width: 500px;">
                            <div class="input-group-prepend"><span class="input-group-text"><i
                                        class="fa fa-user-o"></i></span></div>{{ form.nombre }}
                        </div>
                    </div>
                    <div class="form-group"><label for="from-email">Email</label><span class="required-input">*</span>
                        <div class="input-group" style="width: 500px;">
                            <div class="input-group-prepend"><span class="input-group-text"><i
                                        class="fa fa-envelope-o"></i></span></div>{{ form.email }}
                        </div>
                    </div>
                    <div class="form-group">

                        <div class="form-group"><label for="from-phone">Telefono</label><span
                                class="required-input">*</span>
                            <div class="input-group" style="width: 500px;">
                                <div class="input-group-prepend"><span class="input-group-text"><i
                                            class="fa fa-phone"></i></span></div>{{ form.telefono }}
                            </div>

                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-group"><label for="from-calltime">Horario de Contacto</label>
                            <div class="input-group" style="width: 500px;">
                                <div class="input-group-prepend"><span class="input-group-text"><i
                                            class="fa fa-clock-o"></i></span></div>{{ form.horario }}
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group" style="width: 500px;"><label
                            for="from-comments">Comentarios</label><small>&nbsp;(Opcional)</small>{{ form.comentarios }}
                    </div>
                    <div class="form-group">
                        <div class="form-row" style="width: 500px;">
                            <div class="col"><button class="btn btn-primary btn-block" type="reset"><i
                                        class="fa fa-undo"></i> Resetear</button></div>
                            <div class="col"><button class="btn btn-primary btn-block" type="submit">Enviar&nbsp;<i
                                        class="fa fa-chevron-circle-right"></i></button></div>
                        </div>
                    </div>
        </form>
        <hr class="d-flex d-md-none">
    </div>
    <div class="col-12 col-md-6">
        <h2 class="h4"><i class="fa fa-location-arrow"></i> Encontranos</h2>
        <div class="form-row">
            <div class="col-12">
                <div class="static-map"><img class="img-fluid" src="{% static 'productos/images/mapa.png' %}"
                        alt="Ubicacion" width="317px" style="padding: 30px 0px 30px 0px; width: 500px;"></div>
            </div>
            <div class="col-sm-6 col-md-12 col-lg-6">
                <h2 class="h4"><i class="fa fa-user"></i> Nuestra Info</h2>
                <div><span><strong>Dakota Store</strong><br></span></div>
                <div><span>unemail@gmail.com</span></div>
                <div><span>www.unwebsite.com</span></div>
                <hr class="d-sm-none d-md-block d-lg-none">
            </div>
            <div class="col-sm-6 col-md-12 col-lg-6">
                <h2 class="h4"><i class="fa fa-location-arrow"></i> Nuestra Direccion</h2>
                <div></div>
                <div><span>Calle 123 entre calle y calle</span></div>
                <div><span>Palermo, CABA, 1426</span></div>
                <div><abbr data-toggle="tooltip" data-placement="top" title="Office Phone: 555-867-5309">Tel:</abbr>
                    +5491100000000</div>
                <hr class="d-sm-none">
            </div>
        </div>
    </div>
</div>
<hr>
{% include 'footer.html' %}
{% endblock body_block %}

productos/templates/productos/detail.html
{% extends 'header.html' %}

{% block body_block %}
<div class="container">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'productos:index'%}" style="color: black;"><span>Inicio</span></a>
        </li>
        <li class="breadcrumb-item"><a href="#" style="color: black;"><span>Productos</span></a></li>
        <li class="breadcrumb-item"><strong><span>{{producto.nombre}}</span></strong></li>
    </ol>
    <div class="container" style="margin-bottom: 75px;">
        <div class="row">
            <div class="col-md-7">
                <div class="row">
                    <div class="col-md-12"><img class="img-thumbnail img-fluid center-block"
                            src="{{ producto.imagen.url }}" style="height: auto; width: auto;"></div>
                </div>
                <div class="row">
                    {% if producto.imagen2 %}
                    <div class="col-6 col-sm-6 col-md-6"><img class="img-thumbnail img-fluid center-block"
                            src="{{ producto.imagen2.url }}"></div>
                    {% endif %}
                    {% if producto.imagen3 %}
                    <div class="col-6 col-sm-6 col-md-6"><img class="img-thumbnail img-fluid center-block"
                            src="{{ producto.imagen3.url }}"></div>
                    {% endif %}
                </div>
                <div class="row">
                    {% if producto.imagen4 %}
                    <div class="col-6 col-sm-6 col-md-6"><img class="img-thumbnail img-fluid center-block"
                            src="{{ producto.imagen4.url }}"></div>
                    {% endif %}
                    {% if producto.imagen5 %}
                    <div class="col-6 col-sm-6 col-md-6"><img class="img-thumbnail img-fluid center-block"
                            src="{{ producto.imagen5.url }}"></div>
                    {% endif %}
                </div>
            </div>
            <div class="col-md-5">
                <h1>{{producto.nombre}}</h1>
                <p>{{producto.descripcion}}</p>
                {% if producto.caracteristica1 %}
                <p><i class="fa fa-check"></i>Carac 1</p>
                {% endif %}
                {% if producto.caracteristica2 %}
                <p><i class="fa fa-check"></i>Carac 2</p>
                {% endif %}
                {% if producto.caracteristica3 %}
                <p><i class="fa fa-check"></i>Carac 3</p>
                {% endif %}
                {% if producto.caracteristica4 %}
                <p><i class="fa fa-check"></i>Carac 4</p>
                {% endif %}
                <h4 class="text-success" style="height:58px;color:rgb(0,0,0);font-size:30px;"><i class="fa fa-usd"
                        style="height:38px;"></i>{{producto.precio}}</h4><button
                    class="btn btn-dark btn-lg center-block" type="button"><i class="fa fa-cart-plus"></i>Agregar al
                    carrito</button>
            </div>
        </div>
    </div>
    <hr>
    <div class="container">
        <h2 class="text-center">PRODUCTOS RELACIONADOS</h2><br>
        <div class="row">
            {% for r in related %}
            <div class="col-md-3" style="padding-bottom: 20px;">
                <div class="card"><a href="{% url 'productos:producto_detail' slug=r.slug %}"><img
                            class="card-img-top w-100 d-block" src="{{ r.imagen.url }}"
                            style="width: auto; height: 150px;" /></a>
                    <div class="card-body"><a href="{% url 'productos:producto_detail' slug=r.slug %}"
                            style="color: #465765; font-weight: 500; font-size: 0.90rem;"><span>{{r.nombre}}</span></a>
                        <h5>{{r.precio}}</h5>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<hr>
{% include 'footer.html' %}
{% endblock %}

productos/templates/productos/index.html
{% extends 'header.html' %}
{% load static %}
{% block body_block %}

<div class="container">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="{% static 'productos/images/tacos.jpg' %}" alt="First slide"
                    style="height: 500px; width: 100%;">
                <div class="carousel-caption d-none d-md-block">

                    <p></p>
                </div>
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static 'productos/images/jeans.jpg' %}" alt="Second slide"
                    style="height: 500px; width: 100%;">
                <div class="carousel-caption d-none d-md-block">

                    <p></p>
                </div>
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static 'productos/images/cartera.jpg' %}" alt="Third slide"
                    style="height: 500px; width: 100%;">
                <div class="carousel-caption d-none d-md-block">

                    <p></p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <h3 class="text-center"><br><strong>INFORMACION IMPORTANTE / LEER ATENTAMENTE</strong><br></h3>
    <p class="text-center"><br>UNA VEZ QUE SELECCIONES TUS PRENDAS Y CONFIRMES EL PEDIDO ESPERA NUESTRO MENSAJE VIA
        WHATSAPP PARA COORDINAR EL PAGO Y ENTREGA DE LA MERCADERIA.<br><br></p>
    <div class="container" style="padding-top: 25px; padding-bottom: 50px;">
        <div class="row">
            <div class="col-md-6 col-lg-2">
                <h5>Categorias Principales</h5>
                <p><a href="">Mujer</a></p>
                <p><a href="">Sale</a></p>
            </div>
            <div class="col-md-6 col-lg-10">
                <div class="row">
                    {% for p in object_list reversed %}
                    <div class="col-md-3" style="padding-bottom: 20px;">
                        <div class="card"><a href="{% url 'productos:producto_detail' slug=p.slug %}"><img
                                    class="card-img-top w-100 d-block" src="{{ p.imagen.url }}"
                                    style="width: auto; height: 150px;" /></a>
                            <div class="card-body"><a href="{% url 'productos:producto_detail' slug=p.slug %}"
                                    style="color: #465765; font-weight: 500; font-size: 0.90rem;"><span>{{p.nombre}}</span></a>
                                <h5>{{p.precio}}</h5>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="container-fluid" style="margin-left: 300px;"><a href="{% url 'productos:list' %}">
                        <button class="btn btn-link border-pretty" type="button"
                            style="background-color:#ce9c95; color: #ffffff;">VER TODOS
                            LOS
                            PRODUCTOS<i class="icon ion-android-arrow-forward"></i></button></a>
                </div>
            </div>
        </div>
    </div>
</div>
<hr>
{% include 'footer.html' %}
{% endblock %}

productos/templates/productos/list.html
{% extends 'header.html' %}
{% load static %}
{% block body_block %}
<div class="container">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'productos:index'%}" style="color: black;"><span>Inicio</span></a>
        </li>
        <li class="breadcrumb-item"><a href="#" style="color: black;"><strong><span>Productos</span></strong></a></li>
    </ol>
    <div class="row">
        {% for p in object_list reversed %}
        <div class="col-md-3" style="padding-bottom: 20px;">
            <div class="card"><a href="{% url 'productos:producto_detail' slug=p.slug %}"><img
                        class="card-img-top w-100 d-block" src="{{ p.imagen.url }}"
                        style="width: auto; height: 150px;" /></a>
                <div class="card-body"><a href="{% url 'productos:producto_detail' slug=p.slug %}"
                        style="color: #465765; font-weight: 500; font-size: 0.90rem;"><span>{{p.nombre}}</span></a>
                    <h5>{{p.precio}}</h5>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% include 'footer.html' %}
{% endblock %}