Pagina/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls)),
        path('admin/', admin.site.urls),
        path('', include('productos.urls', namespace='productos')),
        path('accounts/', include('accounts.urls', namespace='accounts')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns = [
        path('admin/', admin.site.urls),
        path('', include('productos.urls', namespace='productos')),
        path('accounts/', include('accounts.urls', namespace='accounts')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html',
                                                redirect_field_name='productos:index'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='productos/index.html'), name="logout"),
    path('registration/', views.SignUp.as_view(), name='registration'),
]

productos/urls.py
from django.urls import path
from . import views
app_name = 'productos'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('producto/<slug:slug>/',
         views.ProductoDetailView.as_view(), name='producto_detail'),
    path('contacto/', views.contactoView, name='contacto'),
    path('crear/', views.AgregarProducto.as_view(), name='crear'),
    path('productos/', views.ProductList.as_view(), name='list')
]

templates/footer.html
<div class="footer-clean">
    <footer>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-sm-4 col-md-3 item">
                    <h3>Navegacion</h3>
                    <ul>
                        <li><a href="{% url 'productos:index' %}">Inicio</a></li>
                        <li><a href="{% url 'productos:list' %}">Productos</a></li>
                        <li><a href="#">Sale</a></li>
                    </ul>
                </div>
                <div class="col-sm-4 col-md-3 item">
                    <h3>Contacto</h3>
                    <ul>
                        <li><a href="#">+54911000000</a></li>
                        <li><a href="#">unemail@gmail.com</a></li>
                        <li><a href="#">Calle 123 Palermo, CABA</a></li>
                    </ul>
                </div>
                <div class="col-sm-4 col-md-3 item">
                    <h3>Nosotros</h3>
                    <ul>
                        <li><a href="#">Dato 1</a></li>
                        <li><a href="#">Dato 2</a></li>
                        <li><a href="#">Dato 3</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 item social">
                    <a href="#"><i class="icon ion-social-facebook"></i></a>
                    <a href="#"><i class="icon ion-social-twitter"></i></a>
                    <a href="#"><i class="icon ion-social-snapchat"></i></a>
                    <a href="https://www.instagram.com/dakotastoreok/" target="blank"><i
                            class="icon ion-social-instagram"></i></a>
                    <p class="copyright">Dakota Store© 2020</p>
                </div>
            </div>
        </div>
    </footer>
</div>

templates/header.html
<!DOCTYPE html>
<html>
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dakota Store</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'productos/CSS/master.css'%}">
    <link rel="stylesheet" href="{% static 'productos/CSS/Footer-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'productos/CSS/ionicons.min.css' %}">
</head>

<body>
    <nav class="navbar navbar-light navbar-expand-md navigation-clean-search">
        <div class="container"><a class="navbar-brand" href="{% url 'productos:index'%}">Dakota Store</a><button
                class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle
                    navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav">
                    <li class="dropdown nav-item" role="presentation">
                        <a class="dropdown-toggle nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false"
                            href="#">Productos</a>
                        <div class="dropdown-menu" role="menu">
                            <a class="dropdown-item" role="presentation" href="{% url 'productos:list' %}">Todos</a>
                            <a class="dropdown-item" role="presentation" href="#">Zapatos</a>
                            <a class="dropdown-item" role="presentation" href="#">Vestidos</a>
                            <a class="dropdown-item" role="presentation" href="#">Botas</a>
                        </div>
                    </li>
                    <li class="nav-item" role="presentation"><a class="nav-link"
                            href="{% url 'productos:contacto' %}">Contacto</a></li>
                </ul>
                <form class="form-inline mr-auto" target="_self">
                    <div class="form-group"><label for="search-field"><i class="fa fa-search"></i></label><input
                            class="form-control search-field" type="search" name="search" id="search-field"
                            placeholder="Buscar..." /></div>
                </form>
                {% if user.is_staff%}
                <a class="btn btn-light action-button" role="button" href="{% url 'productos:crear' %}"
                    style="background-color: aquamarine;">Agregar Producto</a>
                <a class="btn btn-light action-button" type="button" href="{% url 'accounts:logout'%}"
                    style="background-color: #ce9c95;">Cerrar Sesion</a>
                {% else %}
                {% if user.is_authenticated %}
                <a class="btn btn-light action-button" role="button" href="">{{user.email}}</a>
                <a class="btn btn-light action-button" type="button" href="{% url 'accounts:logout'%}"
                    style="background-color: #ce9c95;">Cerrar Sesion</a>
                {% else %}
                <a class="btn btn-light action-button" role="button" href="{% url 'accounts:login'%}">Iniciar Sesion</a>
                <a class="btn btn-light action-button" role="button" href="{% url 'accounts:registration'%}"
                    style="background-color: #ce9c95;">Registrarse</a>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </nav>
    {% block body_block %}

    {% endblock %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.bundle.min.js"></script>
</body>

</html>